on: ["push", "pull_request"]
name: "Nexo CI Pipeline"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Check formatting
        run: yarn format

      - name: Generate coverage report
        run: yarn coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.json
          flags: unittests
          name: nexo-codecov
          fail_ci_if_error: true
